#!/usr/bin/env php
<?php
require_once( "lib/DrupalRest.php" );

date_default_timezone_set("Europe/London");

$site = "uos-test.ecs.soton.ac.uk";
$user = "automatic-updates";
$pass = "muskrat";

$filter = "nid=5263";

$d = new DrupalREST( $site,$user,$pass );
var_dump( $d->get_nodes($filter) );
