#!/usr/bin/env php
<?php
require_once( "lib/DrupalRest.php" );

date_default_timezone_set("Europe/London");

$site = "uos-test.ecs.soton.ac.uk";
$user = "automatic-updates";
$pass = "muskrat";

$content_type = "automatic_ecs_person";
$id_field = "field_ecs_person_pinumber";
$hash_field = "field_sync_hash";
$records_file = "data.json";


$records = json_decode( file_get_contents($records_file),true);

$d = new DrupalREST( $site,$user,$pass );
$d->sync(array(
	"content_type" => $content_type, 
	"id_field" => $id_field,
	"hash_field" => $hash_field,
	"records" => $records,
#	"update" => "update_person_record",
#	"create" => "create_person_record",
));
exit;
