#!/usr/bin/env php
<?php
require_once( "DrupalRest.php" );

date_default_timezone_set("Europe/London");

$site = "cjg.drupal";
$user = "automatic-updates";
$pass = "muskrat";

$content_type = "person";
$id_field = "field_id_number";
$records_file = "data.json";


$records = json_decode( file_get_contents($records_file),true);

$d = new DrupalREST( $site,$user,$pass );
$d->sync(array(
	"content_type" => $content_type, 
	"id_field" => $id_field,
	"records" => $records,
	"update" => "update_person_record",
	"create" => "create_person_record",
));
exit;

function update_person_record( $node, $record )
{
	$data = array();
	$data["title"] = $record["forename"]." ".$record["surname"];
	$data["field_data"] = json_encode( $record );
	return $data;
}

function create_person_record( $record )
{
	$data = array();
	$data["title"] = $record["forename"]." ".$record["surname"];
	//$data["alias"] = "people/".strtolower($record["forename"]."-".$record["surname"]);
	$data["field_data"] = json_encode( $record );
	return $data;
}

